### ISSUE TITLE
Incrementation of the recordVersion Property in the Metadata Document

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#75]
**Describe the bug**
I register a metadata record and a document for a specific schema. I update only my metadata record. The record is updated but the recordVersion number is not incremented. It is meant by recordVersion, the version of the metadata record and not the document or?
 
**To Reproduce**
1. Register a schema (schema record and schema document)
2. Ingest a metadata document (metadata record and metadata document)
3. Update only the metadata record

**Expected behavior**
The recordVersion number should be incremented.

**Comment by VolkerHartmann** [comment]
In former versions it was handled like you described. In the meantime there was a change in behavior since version 0.3.0.
There may be different versions of a metadata/schema document only the last 'version' of the linked metadata/schema record is stored. For accessing a document only the current authentication settings are used. Users who cannot read the current version are not allowed to read old versions even if they had the access permission then. 
See also #27, #52.
